name: in_app_updates
description: Flutter project that help use in_app_updates for android and ios.
version: 0.0.1
repository: https://github.com/smenateam/in_app_updates

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ru.tistol.in_app_updates
        pluginClass: InAppUpdatesPlugin
      ios:
        pluginClass: InAppUpdatesPlugin
